Fix to pass tests.
BulkTests.cs(33,41): error CS7036: There is no argument given that corresponds to the required formal parameter 'callerWillDisposeHttpClient' of 'XmlHttpClient.XmlHttpClient(string, string, string, HttpClient, bool)' [/home/travis/build/developerforce/Force.com-Toolkit-for-NET/tests/ForceToolkitForNET.Tests/ForceToolkitForNET.Tests.csproj]
BulkTests.cs(62,41): error CS7036: There is no argument given that corresponds to the required formal parameter 'callerWillDisposeHttpClient' of 'XmlHttpClient.XmlHttpClient(string, string, string, HttpClient, bool)' [/home/travis/build/developerforce/Force.com-Toolkit-for-NET/tests/ForceToolkitForNET.Tests/ForceToolkitForNET.Tests.csproj]
CommonFunctionalTests.cs(204,44): error CS7036: There is no argument given that corresponds to the required formal parameter 'callerWillDisposeHttpClient' of 'XmlHttpClient.XmlHttpClient(string, string, string, HttpClient, bool)' [/home/travis/build/developerforce/Force.com-Toolkit-for-NET/tests/ForceToolkitForNET.Tests/ForceToolkitForNET.Tests.csproj]
The command "dotnet test tests/ForceToolkitForNET.Tests.sln /p:CollectCoverage=true" exited with 1.